Makefile.am: supply missing $(LIBGUESTFS_CFLAGS)
Common C source code pulled into virt-builder, virt-index-validate and
virt-customize #includes "guestfs.h", but the guestfs-tools makefiles of
those modules do not add $(LIBGUESTFS_CFLAGS) to the respective module
CFLAGS macros. The command

> $ ../libguestfs/run make

produces errors such as

>   CC       ../common/edit/libcustomize_a-file-edit.o
> In file included from ../common/edit/file-edit.c:46:
> ../common/edit/file-edit.h:22:10: fatal error: guestfs.h: No such file or directory
>    22 | #include <guestfs.h>
>       |          ^~~~~~~~~~~

Add the missing $(LIBGUESTFS_CFLAGS) instances.

Signed-off-by: Laszlo Ersek <lersek@redhat.com>
Message-Id: <20210906114314.14750-3-lersek@redhat.com>
Acked-by: Richard W.M. Jones <rjones@redhat.com>