inspector/inspector.c: Remove extra cases covered by default
In GCC 14:

inspector.c: In function ‘do_xpath’:
inspector.c:770:3: error: case value ‘5’ not in enumerated type ‘xmlXPathObjectType’ [-Werror=switch]
  770 |   case XPATH_POINT:
      |   ^~~~
inspector.c:771:3: error: case value ‘6’ not in enumerated type ‘xmlXPathObjectType’ [-Werror=switch]
  771 |   case XPATH_RANGE:
      |   ^~~~
inspector.c:772:3: error: case value ‘7’ not in enumerated type ‘xmlXPathObjectType’ [-Werror=switch]
  772 |   case XPATH_LOCATIONSET:
      |   ^~~~

We already have a default case here, remove the other cases.

(cherry picked from commit 9d2ac9c9b48bf34f5fc3485303143302ead4cb4f)