Makefile.am: fix $(LIBGUESTFS_CFLAGS) typo for virt-ls
Commit 4354a3126152 ("Add build system.", 2021-03-11) added
$(LIBGUESTFS_LIBS) to "virt_ls_CFLAGS" and "virt_ls_LDADD" both.

Correct the former; it should carry $(LIBGUESTFS_CFLAGS). Currently, the
command

> $ ../libguestfs/run make

produces the error

>   CC       virt_ls-ls.o
> ls.c:47:10: fatal error: guestfs.h: No such file or directory
>    47 | #include "guestfs.h"
>       |          ^~~~~~~~~~~

Fixes: 4354a3126152a2748cc9097cba139b3908ccc342
Signed-off-by: Laszlo Ersek <lersek@redhat.com>
Message-Id: <20210906114314.14750-2-lersek@redhat.com>
Acked-by: Richard W.M. Jones <rjones@redhat.com>