gnulib/lib/argmatch.c: Include right header for gettext
argmatch.c: In function ‘argmatch_invalid’:
argmatch.c:32:18: warning: implicit declaration of function ‘gettext’ [-Wimplicit-function-declaration]
   32 | #define _(msgid) gettext (msgid)
      |                  ^~~~~~~
argmatch.c:110:27: note: in expansion of macro ‘_’
  110 |                         ? _("invalid argument %s for %s")
      |                           ^
argmatch.c:32:18: warning: incompatible implicit declaration of built-in function ‘gettext’ [-Wbuiltin-declaration-mismatch]
   32 | #define _(msgid) gettext (msgid)
      |                  ^~~~~~~
argmatch.c:110:27: note: in expansion of macro ‘_’
  110 |                         ? _("invalid argument %s for %s")
      |                           ^
argmatch.c: In function ‘argmatch_valid’:
argmatch.c:32:18: warning: incompatible implicit declaration of built-in function ‘gettext’ [-Wbuiltin-declaration-mismatch]
   32 | #define _(msgid) gettext (msgid)
      |                  ^~~~~~~
argmatch.c:129:10: note: in expansion of macro ‘_’
  129 |   fputs (_("Valid arguments are:"), stderr);
      |          ^

(cherry picked from commit 9cd84a2ea15a0b93fa53c083258ce1df67279e92)