build: Reduce -Wformat-overflow=2 to =1.
GCC 9 gives this error:

qemuopts.c: In function 'qemuopts_to_config_channel':
qemuopts.c:987:29: error: '%.*s' directive output between 0 and 2147483647 bytes may exceed minimum required size of 4095 [-Werror=format-overflow=]
  987 |             fprintf (fp, "  %.*s = ", (int) k, values[j]);
      |                             ^~~~
qemuopts.c:987:26: note: assuming directive output of 1 byte
  987 |             fprintf (fp, "  %.*s = ", (int) k, values[j]);
      |                          ^~~~~~~~~~~

See discussion at the following GCC bug:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=88993
(cherry picked from commit b26bd778b58b78eb59503413fd5b41ac23725690)